apiVersion: v1
kind: Pod
metadata:
  name: gestion-station-ski
spec:
  containers:
    - name: mysqldb
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: stationSki
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
      ports:
        - containerPort: 3306

    - name: app
      image: zieddr8/gestion-station-ski
      env:
        - name: SPRING_APPLICATION_JSON
          value: '{
            "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "password",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      ports:
        - containerPort: 8089